#!/usr/bin/env python3
"""
extract_turns.py — parse a Claude Code .jsonl transcript into numbered turns,
and copy verbatim turn text BY ID (never regenerated by an LLM).

Two subcommands:
  index   <transcript.jsonl>            -> emits [{id, role, text}, ...] as JSON (for the Sonnet triage agent)
  collect <transcript.jsonl> <ids...>   -> emits {id: verbatim_text, ...} for the given ids (verbatim copy)

Design contract (see memory: llm-extractif-verbatim-par-code):
  - The LLM DESIGNATES which turns matter (returns ids). This script COPIES the text.
  - A dict[id] lookup cannot hallucinate. Verbatim fidelity is guaranteed here, not in the model.

Robustness: the .jsonl schema is UNDOCUMENTED and Anthropic may change it.
  - `content` is polymorphic (str OR list of blocks) — both handled, unknown -> logged, not crashed.
  - On any structural failure, exit code 2 with a diagnostic on stderr so the skill can fall back to os-only.
  - --max-chars caps per-turn text to avoid an obese checkpoint (default 4000).
"""
import json
import sys

SCHEMA_NOTE = "expected Claude Code transcript: one JSON event per line, type in {user,assistant}, message.content str|list"


def _extract_text(content):
    """Flatten a message.content (str or list of blocks) to plain text. Unknown blocks -> placeholder."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for b in content:
            if not isinstance(b, dict):
                continue
            t = b.get("type")
            if t == "text":
                parts.append(b.get("text", ""))
            elif t == "tool_use":
                parts.append(f"[tool_use:{b.get('name', '?')}]")
            elif t == "tool_result":
                parts.append("[tool_result]")
            else:
                parts.append(f"[{t or 'unknown-block'}]")
        return " ".join(parts)
    # Unknown shape: don't crash, signal it.
    return None


def load_turns(path, max_chars=4000):
    """Return list of {id, role, text}. Raises RuntimeError on structural failure (-> os-only fallback)."""
    try:
        raw = open(path, encoding="utf-8").read().splitlines()
    except OSError as e:
        raise RuntimeError(f"cannot read transcript: {e}")

    turns = []
    tid = 0
    unknown_content = 0
    for line in raw:
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
        except json.JSONDecodeError:
            continue  # tolerate a stray non-JSON line
        if not isinstance(r, dict):
            continue
        if r.get("type") not in ("user", "assistant"):
            continue
        msg = r.get("message", {})
        if not isinstance(msg, dict):
            continue
        txt = _extract_text(msg.get("content"))
        if txt is None:
            unknown_content += 1
            continue
        txt = txt.strip()
        if not txt:
            continue
        # drop system-injected pure tool-result user turns
        if r.get("type") == "user" and txt.startswith("[tool_result"):
            continue
        tid += 1
        turns.append({"id": tid, "role": r["type"], "text": txt[:max_chars]})

    if tid == 0:
        raise RuntimeError(f"no user/assistant turns parsed — schema drift? ({SCHEMA_NOTE})")
    if unknown_content and unknown_content > tid:
        raise RuntimeError(f"majority of turns had unknown content shape ({unknown_content}) — schema drift?")
    return turns


def main(argv):
    if len(argv) < 3:
        print("usage: extract_turns.py <index|collect> <transcript.jsonl> [ids...]", file=sys.stderr)
        return 2
    cmd, path = argv[1], argv[2]
    try:
        turns = load_turns(path)
    except RuntimeError as e:
        print(f"PARSE_FAILED: {e}", file=sys.stderr)
        return 2  # skill sees non-zero -> os-only fallback

    if cmd == "index":
        json.dump(turns, sys.stdout, ensure_ascii=False)
        return 0

    if cmd == "collect":
        try:
            ids = {int(x) for x in argv[3:]}
        except ValueError:
            print("collect: ids must be integers", file=sys.stderr)
            return 2
        by_id = {t["id"]: t["text"] for t in turns}
        out = {str(i): by_id[i] for i in sorted(ids) if i in by_id}
        json.dump(out, sys.stdout, ensure_ascii=False, indent=1)
        return 0

    print(f"unknown subcommand: {cmd}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
