#!/usr/bin/env python3
"""
extract_turns.py — parse a Claude Code .jsonl transcript into numbered turns,
and copy verbatim turn text BY ID (never regenerated by an LLM).

Three subcommands:
  index   <transcript.jsonl>            -> emits [{id, role, text}, ...] as JSON (for the Sonnet triage agent)
  collect <transcript.jsonl> <ids...>   -> emits {id: verbatim_text, ...} for the given ids (verbatim copy)
  harvest <transcript.jsonl>            -> emits [{id, fields:{...}}, ...] from `<!-- ckpt ... -->` trailers
                                          in ASSISTANT turns (author-distilled meat; primary path — 0 LLM)

Design contract (see memory: llm-extractif-verbatim-par-code):
  - The LLM DESIGNATES which turns matter (returns ids). This script COPIES the text.
  - A dict[id] lookup cannot hallucinate. Verbatim fidelity is guaranteed here, not in the model.

Robustness: the .jsonl schema is UNDOCUMENTED and Anthropic may change it.
  - `content` is polymorphic (str OR list of blocks) — both handled, unknown -> logged, not crashed.
  - On any structural failure, exit code 2 with a diagnostic on stderr so the skill can fall back to os-only.
  - --max-chars caps per-turn text to avoid an obese checkpoint (default 4000).
"""
import json
import os
import re
import sys

SCHEMA_NOTE = "expected Claude Code transcript: one JSON event per line, type in {user,assistant}, message.content str|list"

# Author-distilled checkpoint trailer emitted per the user's global CLAUDE.md rule.
# Invisible when rendered (HTML comment), greppable on disk. See reference.md § Trailer harvest.
_CKPT_RE = re.compile(r"<!--\s*ckpt\b(.*?)-->", re.DOTALL)
# 10 of the 12 taxonomy signals — assistant-side only. `correction` + `preference`
# are user-authored (self-tagging can't reach them) → left to extraction by design.
_CKPT_FIELDS = ("decision", "reasoning", "learning", "pivot", "rejected",
                "constraint", "assumption", "open", "definition", "refs")


# ── Secret scrub (collect only) ──────────────────────────────────────────
# The meat is copied verbatim BY DESIGN, but a transcript can quote a live
# secret (a key pasted mid-session). We mask a NARROW, high-precision set of
# unambiguous secret SHAPES before the text lands on disk — precision over
# recall, so prose is never clobbered. Applied in `collect` only (the copy that
# reaches the file); `index`/`harvest` are unaffected. Disable: CHECKPOINT_NO_REDACT=1.
_REDACT_PATTERNS = [
    (re.compile(r"-----BEGIN[^-]*PRIVATE KEY-----.*?-----END[^-]*PRIVATE KEY-----", re.DOTALL), "PRIVATE-KEY"),
    (re.compile(r"\bsk-ant-[A-Za-z0-9_-]{20,}"), "ANTHROPIC-KEY"),
    (re.compile(r"\bsk-[A-Za-z0-9]{20,}"), "API-KEY"),
    (re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "AWS-ACCESS-KEY"),
    (re.compile(r"\bgh[pousr]_[A-Za-z0-9]{30,}"), "GITHUB-TOKEN"),
    (re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}"), "SLACK-TOKEN"),
    (re.compile(r"\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}"), "JWT"),
]
# key=value / key: value assignments — mask only the value, keep the key visible.
_REDACT_ASSIGN = re.compile(r"(?i)\b(password|passwd|secret|token|api[_-]?key)(\s*[:=]\s*)(\S{6,})")


def _redact(text):
    """Mask unambiguous secret shapes. No-op on ordinary prose (precision-first)."""
    if os.environ.get("CHECKPOINT_NO_REDACT"):
        return text
    for rx, label in _REDACT_PATTERNS:
        text = rx.sub(f"[REDACTED:{label}]", text)
    text = _REDACT_ASSIGN.sub(lambda m: f"{m.group(1)}{m.group(2)}[REDACTED]", text)
    return text


def _parse_trailer(block):
    """Parse the inner text of one `<!-- ckpt ... -->` block into {field: value}. Unknown lines ignored."""
    fields = {}
    for line in block.splitlines():
        line = line.strip()
        if not line or ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip().lower()
        val = val.strip()
        if key in _CKPT_FIELDS and val:
            fields.setdefault(key, []).append(val)
    return {k: (v if len(v) > 1 else v[0]) for k, v in fields.items()}


def _extract_text(content):
    """Flatten a message.content (str or list of blocks) to plain text. Unknown blocks -> placeholder."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for b in content:
            if not isinstance(b, dict):
                continue
            t = b.get("type")
            if t == "text":
                parts.append(b.get("text", ""))
            elif t == "tool_use":
                parts.append(f"[tool_use:{b.get('name', '?')}]")
            elif t == "tool_result":
                parts.append("[tool_result]")
            else:
                parts.append(f"[{t or 'unknown-block'}]")
        return " ".join(parts)
    # Unknown shape: don't crash, signal it.
    return None


def load_turns(path, max_chars=4000):
    """Return list of {id, role, text}. Raises RuntimeError on structural failure (-> os-only fallback)."""
    try:
        raw = open(path, encoding="utf-8").read().splitlines()
    except OSError as e:
        raise RuntimeError(f"cannot read transcript: {e}")

    turns = []
    tid = 0
    unknown_content = 0
    for line in raw:
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
        except json.JSONDecodeError:
            continue  # tolerate a stray non-JSON line
        if not isinstance(r, dict):
            continue
        if r.get("type") not in ("user", "assistant"):
            continue
        msg = r.get("message", {})
        if not isinstance(msg, dict):
            continue
        txt = _extract_text(msg.get("content"))
        if txt is None:
            unknown_content += 1
            continue
        txt = txt.strip()
        if not txt:
            continue
        # drop system-injected pure tool-result user turns
        if r.get("type") == "user" and txt.startswith("[tool_result"):
            continue
        tid += 1
        turns.append({"id": tid, "role": r["type"], "text": txt[:max_chars]})

    if tid == 0:
        raise RuntimeError(f"no user/assistant turns parsed — schema drift? ({SCHEMA_NOTE})")
    if unknown_content and unknown_content > tid:
        raise RuntimeError(f"majority of turns had unknown content shape ({unknown_content}) — schema drift?")
    return turns


def main(argv):
    if len(argv) < 3:
        print("usage: extract_turns.py <index|collect> <transcript.jsonl> [ids...]", file=sys.stderr)
        return 2
    cmd, path = argv[1], argv[2]
    try:
        turns = load_turns(path)
    except RuntimeError as e:
        print(f"PARSE_FAILED: {e}", file=sys.stderr)
        return 2  # skill sees non-zero -> os-only fallback

    if cmd == "index":
        json.dump(turns, sys.stdout, ensure_ascii=False)
        return 0

    if cmd == "harvest":
        # Parse ckpt trailers from ASSISTANT turns. Harvest from UNTRUNCATED text
        # (trailers sit at the end of a turn; the index cap could clip them).
        try:
            full = load_turns(path, max_chars=10**9)
        except RuntimeError as e:
            print(f"PARSE_FAILED: {e}", file=sys.stderr)
            return 2
        out = []
        for t in full:
            if t["role"] != "assistant":
                continue
            blocks = _CKPT_RE.findall(t["text"])
            if not blocks:
                continue
            # keep the LAST trailer in the turn (the canonical end-of-answer one)
            fields = _parse_trailer(blocks[-1])
            if fields:
                out.append({"id": t["id"], "fields": fields})
        json.dump(out, sys.stdout, ensure_ascii=False, indent=1)
        return 0

    if cmd == "collect":
        try:
            ids = {int(x) for x in argv[3:]}
        except ValueError:
            print("collect: ids must be integers", file=sys.stderr)
            return 2
        by_id = {t["id"]: t["text"] for t in turns}
        out = {str(i): _redact(by_id[i]) for i in sorted(ids) if i in by_id}
        json.dump(out, sys.stdout, ensure_ascii=False, indent=1)
        return 0

    print(f"unknown subcommand: {cmd}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
